=== aweiker/generals/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/aweiker/generals/main/schema.json",
    "description": "Defines an evony General",
    "type": "object",
    "additionalProperties": false,
    "required": ["name", "skill", "specialties"],

    "properties": {
        "$schema": {
            "type": "string",
            "description": "The reference to this schema"
        },
        "name": {
            "type": "string",
            "description": "The name of the general"
        },
        "skill": {
            "description": "The primary skill of the general.",
            "$ref": "#/$defs/skill"
        },
        "ascensions": {
            "type": "array",
            "description": "The skills the general has when ascended.",
            "items": { "$ref": "#/$defs/ascensionSkill"},
            "length": 5
        },
        "specialties" : {
            "type": "array",
            "description": "The specialties the general has.",
            "items": {
                "$ref": "#/$defs/specialty"
            },
            "length": 4
        },
        "skin": {
            "$ref": "#/$defs/skin",
            "description": "The skin of the general"
        }
    },

    "$defs": {
        "skill": {
            "type": "object",
            "required": ["title", "description", "buffs"],
            "additionalProperties": false,
            "properties": {
                "title": {
                    "type": "string",
                    "description": "The name of the skill"
                },
                "description": {
                    "type": "string",
                    "description": "A description of the skill as it appears on the general"
                },
                "buffs": {
                    "type": "object",
                    "$ref": "#/$defs/buffs",
                    "description": "The skill buffs the general provides"
                }
            }
        },
        "skin": {
            "type": "object",
            "required": ["title", "buffs"],
            "additionalProperties": false,
            "properties": {
                "title": {
                    "type": "string",
                    "description": "The name of the skin"
                },
                "buffs": {
                    "$ref": "#/$defs/buffs",
                    "description": "The skin buffs the general provides"
                }
            }
        },
        "ascensionSkill": {
            "type": "object",
            "required": ["description", "buffs"],
            "additionalProperties": false,
            "properties": {
                "description": {
                    "type": "string",
                    "description": "A description of the ascension as it appears on the general"
                },
                "buffs": {
                    "$ref": "#/$defs/buffs",
                    "description": "The asscension buffs the general provides"
                }
            }
        },
        "specialty": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string",
                    "description": "The name of the specialty"
                },
                "levels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/buffs"
                    },
                    "minItems": 5,
                    "maxItems" : 5,
                    "length": 5
                }
            }
        },
        "buffs": {
            "type": "object",
            "minProperties": 1,
            "additionalProperties": false,
            "properties": {
                "ground": {
                    "$ref": "#/$defs/attributes",
                    "description": "The buffs the general provides to ground troops"
                },
                "mounted": {
                    "$ref": "#/$defs/attributes",
                    "description": "The buffs the general provides to mounted troops"
                },
                "range": {
                    "$ref": "#/$defs/attributes",
                    "description": "The buffs the general provides to ranged troops"
                },
                "siege": {
                    "$ref": "#/$defs/attributes",
                    "description": "The buffs the general provides to siege troops"
                },
                "enemy_ground": {
                    "$ref": "#/$defs/attributes",
                    "description": "The buffs the general provides to ground troops"
                },
                "enemy_mounted": {
                    "$ref": "#/$defs/attributes",
                    "description": "The buffs the general provides to mounted troops"
                },
                "enemy_range": {
                    "$ref": "#/$defs/attributes",
                    "description": "The buffs the general provides to ranged troops"
                },
                "enemy_siege": {
                    "$ref": "#/$defs/attributes",
                    "description": "The buffs the general provides to siege troops"
                },
                "monster": {
                    "type": "object",
                    "$ref": "#/$defs/attributes",
                    "description": "The buffs the general provides to monsters"
                },
                "marchSize": {
                    "type": "number",
                    "description": "The percent increase in march size the general provides"
                },
                "marchSpeed": {
                    "type": "number",
                    "description": "The percent increase in march speed the general provides"
                },
                "doubleDrop": {
                    "type": "number",
                    "description": "Double drop rate of that the general provides"
                },
                "trainingSpeed": {
                    "type": "number",
                    "description": "The Subordinate Training Speed increase the general provides"
                },
                "deathToSurvival": {
                    "type": "number",
                    "description": "The Death into Survival Rate increase the general provides"
                },
                "deathToWounded": {
                    "type": "number",
                    "description": "The Death turning Wounded Rate increase the general provides"
                }
            }
        },
        "attributes": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "attack": {
                    "type": "number",
                    "description": "The attack value of the general"
                },
                "defense": {
                    "type": "number",
                    "description": "The defense value of the general"
                },
                "hp": {
                    "type": "number",
                    "description": "The hit points of the general"
                }
            }
        }
    }
}

=== aweiker/generals/data/baldwin_iv.json
{
    "$schema": "../schema.json",
    "name": "Baldwin IV",
    "skill": {
        "title": "Suprise Attack",
        "description": "Reduces enemy ranged troops' attack by 30% and enemy siege machines' attack by 20% when General is leading the army.",
        "buffs": {
            "enemy_range": {
                "attack": 30
            },
            "enemy_siege": {
                "attack": 20
            }
        }
    },
    "ascensions": [
        {
            "description": "Enemy Ranged Troop and Siege Machine Attack -5% and HP -10%",
            "buffs": {
                "enemy_range": {
                    "attack": 5,
                    "hp": 10
                },
                "enemy_siege": {
                    "attack": 5,
                    "hp": 10
                }
            }
        },
        {
            "description": "Enemy Ranged Troop and Siege Machine Defense -10%; when General is the Mayor, Training Speed in this Subordinate City +20%",
            "buffs": {
                "enemy_range": {
                    "defense": 10
                },
                "enemy_siege": {
                    "defense": 10
                },
                "trainingSpeed": 20
            }
        },
        {
            "description": "Enemy Ranged Troop and Siege Machine HP -15%; when General is the Mayor, Death into Survival Rate in this Subordinate City +10%",
            "buffs": {
                "enemy_range": {
                    "hp": 15
                },
                "enemy_siege": {
                    "hp": 15
                },
                "deathToSurvival": 10
            }
        },
        {
            "description": "Enemy Ranged Troop and Siege Machine Attack -10% and Defense -10%",
            "buffs": {
                "enemy_range": {
                    "attack": 10,
                    "defense": 10
                },
                "enemy_siege": {
                    "attack": 10,
                    "defense": 10
                }
            }
        },
        {
            "description": "Enemy Ranged Troop and Siege Machine Attack, Defense and HP -10%",
            "buffs": {
                "enemy_range": {
                    "attack": 10,
                    "defense": 10,
                    "hp": 10
                },
                "enemy_siege": {
                    "attack": 10,
                    "defense": 10,
                    "hp": 10
                }
            }
        }
    ],
    "skin": {
        "title": "Divin Guardian - Baldwin IV",
        "buffs": {
            "enemy_ground": {
                "hp": 10
            },
            "enemy_mounted": {
                "hp": 10
            },
            "enemy_range": {
                "attack": 5
            },
            "enemy_siege": {
                "attack": 5
            }
        }
    },
    "specialties": [
        {
            "title": "Mounted Troop Assault",
            "levels": [
                {
                    "mounted": {
                        "attack": 1,
                        "hp": 1
                    }
                },
                {
                    "mounted": {
                        "attack": 1,
                        "hp": 1
                    }
                },
                {
                    "mounted": {
                        "attack": 2,
                        "hp": 2
                    }
                },
                {
                    "mounted": {
                        "attack": 2,
                        "hp": 2
                    }
                },
                {
                    "mounted": {
                        "attack": 4,
                        "hp": 4
                    }
                }
            ]
        },
        {
            "title": "Snipe",
            "levels": [
                {
                    "enemy_ground": {
                        "attack": 1
                    },
                    "enemy_mounted": {
                        "attack": 1
                    },
                    "enemy_range": {
                        "attack": 1
                    },
                    "enemy_siege": {
                        "attack": 1
                    }
                },

                {
                    "enemy_ground": {
                        "attack": 1
                    },
                    "enemy_mounted": {
                        "attack": 1
                    },
                    "enemy_range": {
                        "attack": 1
                    },
                    "enemy_siege": {
                        "attack": 1
                    }
                },
                {
                    "enemy_ground": {
                        "attack": 2
                    },
                    "enemy_mounted": {
                        "attack": 2
                    },
                    "enemy_range": {
                        "attack": 2
                    },
                    "enemy_siege": {
                        "attack": 2
                    }
                },
                {
                    "enemy_ground": {
                        "attack": 2
                    },
                    "enemy_mounted": {
                        "attack": 2
                    },
                    "enemy_range": {
                        "attack": 2
                    },
                    "enemy_siege": {
                        "attack": 2
                    }
                },
                {
                    "enemy_ground": {
                        "attack": 4
                    },
                    "enemy_mounted": {
                        "attack": 4
                    },
                    "enemy_range": {
                        "attack": 4
                    },
                    "enemy_siege": {
                        "attack": 4
                    }
                }
            ]
        },
        {
            "title": "Mounted Troop Ares",
            "levels": [
                {
                    "mounted": {
                        "attack": 1,
                        "defense": 1,
                        "hp": 1
                    }
                },
                {
                    "mounted": {
                        "attack": 1,
                        "defense": 1,
                        "hp": 1
                    }
                },
                {
                    "mounted": {
                        "attack": 2,
                        "defense": 2,
                        "hp": 2
                    }
                },
                {
                    "mounted": {
                        "attack": 2,
                        "defense": 2,
                        "hp": 2
                    }
                },
                {
                    "mounted": {
                        "attack": 4,
                        "defense": 4,
                        "hp": 4
                    }
                }
            ]
        },
        {
            "title": "Battle of Montgisard",
            "levels": [
                {
                    "enemy_range": {
                        "attack": 2,
                        "hp": 1
                    },
                    "enemy_siege": {
                        "attack": 2,
                        "hp": 1
                    }
                },
                {
                    "enemy_range": {
                        "attack": 2,
                        "hp": 1
                    },
                    "enemy_siege": {
                        "attack": 2,
                        "hp": 1
                    }
                },
                {
                    "enemy_range": {
                        "attack": 4,
                        "hp": 2
                    },
                    "enemy_siege": {
                        "attack": 4,
                        "hp": 2
                    }
                },
                {
                    "enemy_range": {
                        "attack": 4,
                        "hp": 2
                    },
                    "enemy_siege": {
                        "attack": 4,
                        "hp": 2
                    }
                },
                {
                    "enemy_range": {
                        "attack": 8,
                        "hp": 4
                    },
                    "enemy_siege": {
                        "attack": 8,
                        "hp": 4
                    }
                }
            ]
        }
    ]
}
